### ISSUE TITLE
Click shortcode to resume editing

### ISSUE THREAD

**Issue by jedateach** [sheadawson/silverstripe-shortcodable#6] opened 2014-09-26 05:00 UTC
It would be super useful to be able to open up a shortcode in the popup box again to continue editing.

Perhaps render something clickable in TinyMCE.

This module is definitely progressing towards a more flexible CMS. Allowing rich content, without requiring users to edit in TinyMCE.

**Comment by sheadawson** [comment] 2016-05-07 11:10
The new placeholders will help with this but still need to fix shortcodes that don't have placeholders. I'll close this issue as it's a less specific duplicate of #11

**Closed by sheadawson** 2016-05-07 11:10 UTC
